TYPO3:
  Flow:
    i18n:
      defaultLocale: 'ru'
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Site': TRUE
    userInterface:
      defaultLanguage: 'ru'
      navigateComponent:
        nodeTree:
          loadingDepth: 1
  # TYPO3CR:
  #   contentDimensions:
  #     'language':
  #       default: 'ru'
  #       defaultPreset: 'ru'
  #       label: 'Language'
  #       icon: 'icon-language'
  #       presets:
  #         'ru':
  #           label: 'Russian'
  #           values: ['ru']
  #           uriSegment: ''
  #         'en':
  #           label: 'English'
  #           values: ['en']
  #           uriSegment: 'en'
